/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.25.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { Uint128, Decimal, InstantiateMsg, Coin, ExecuteMsg, AssetInfo, GatingOptionsMsg, Timestamp, Uint64, Binary, HexBinary, Cw721Coin, Sg721Token, RaffleOptionsMsg, Cw20Coin, Cw721ReceiveMsg, NoisCallback, QueryMsg, QueryFilters, Addr, GatingOptions, RaffleState, AllRafflesResponse, RaffleResponse, RaffleInfo, RaffleOptions, Cw20CoinVerified, ArrayOfString, ConfigResponse, Locks, Uint32 } from "./Raffle.types";
export interface RaffleReadOnlyInterface {
  contractAddress: string;
  config: () => Promise<ConfigResponse>;
  raffleInfo: ({
    raffleId
  }: {
    raffleId: number;
  }) => Promise<RaffleResponse>;
  allRaffles: ({
    filters,
    limit,
    startAfter
  }: {
    filters?: QueryFilters;
    limit?: number;
    startAfter?: number;
  }) => Promise<AllRafflesResponse>;
  allTickets: ({
    limit,
    raffleId,
    startAfter
  }: {
    limit?: number;
    raffleId: number;
    startAfter?: number;
  }) => Promise<ArrayOfString>;
  ticketCount: ({
    owner,
    raffleId
  }: {
    owner: string;
    raffleId: number;
  }) => Promise<Uint32>;
}
export class RaffleQueryClient implements RaffleReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.config = this.config.bind(this);
    this.raffleInfo = this.raffleInfo.bind(this);
    this.allRaffles = this.allRaffles.bind(this);
    this.allTickets = this.allTickets.bind(this);
    this.ticketCount = this.ticketCount.bind(this);
  }

  config = async (): Promise<ConfigResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
  raffleInfo = async ({
    raffleId
  }: {
    raffleId: number;
  }): Promise<RaffleResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      raffle_info: {
        raffle_id: raffleId
      }
    });
  };
  allRaffles = async ({
    filters,
    limit,
    startAfter
  }: {
    filters?: QueryFilters;
    limit?: number;
    startAfter?: number;
  }): Promise<AllRafflesResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      all_raffles: {
        filters,
        limit,
        start_after: startAfter
      }
    });
  };
  allTickets = async ({
    limit,
    raffleId,
    startAfter
  }: {
    limit?: number;
    raffleId: number;
    startAfter?: number;
  }): Promise<ArrayOfString> => {
    return this.client.queryContractSmart(this.contractAddress, {
      all_tickets: {
        limit,
        raffle_id: raffleId,
        start_after: startAfter
      }
    });
  };
  ticketCount = async ({
    owner,
    raffleId
  }: {
    owner: string;
    raffleId: number;
  }): Promise<Uint32> => {
    return this.client.queryContractSmart(this.contractAddress, {
      ticket_count: {
        owner,
        raffle_id: raffleId
      }
    });
  };
}
export interface RaffleInterface extends RaffleReadOnlyInterface {
  contractAddress: string;
  sender: string;
  createRaffle: ({
    assets,
    owner,
    raffleOptions,
    raffleTicketPrice
  }: {
    assets: AssetInfo[];
    owner?: string;
    raffleOptions: RaffleOptionsMsg;
    raffleTicketPrice: AssetInfo;
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
  cancelRaffle: ({
    raffleId
  }: {
    raffleId: number;
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
  claimRaffle: ({
    raffleId
  }: {
    raffleId: number;
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
  updateConfig: ({
    creationCoins,
    feeAddr,
    maxTicketsPerRaffle,
    minimumRaffleDuration,
    name,
    noisProxyAddr,
    noisProxyCoin,
    owner,
    raffleFee
  }: {
    creationCoins?: Coin[];
    feeAddr?: string;
    maxTicketsPerRaffle?: number;
    minimumRaffleDuration?: number;
    name?: string;
    noisProxyAddr?: string;
    noisProxyCoin?: Coin;
    owner?: string;
    raffleFee?: Decimal;
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
  modifyRaffle: ({
    raffleId,
    raffleOptions,
    raffleTicketPrice
  }: {
    raffleId: number;
    raffleOptions: RaffleOptionsMsg;
    raffleTicketPrice?: AssetInfo;
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
  buyTicket: ({
    onBehalfOf,
    raffleId,
    sentAssets,
    ticketCount
  }: {
    onBehalfOf?: string;
    raffleId: number;
    sentAssets: AssetInfo;
    ticketCount: number;
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
  receive: ({
    msg,
    sender,
    tokenId
  }: {
    msg: Binary;
    sender: string;
    tokenId: string;
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
  noisReceive: ({
    callback
  }: {
    callback: NoisCallback;
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
  updateRandomness: ({
    raffleId
  }: {
    raffleId: number;
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
  toggleLock: ({
    lock
  }: {
    lock: boolean;
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
}
export class RaffleClient extends RaffleQueryClient implements RaffleInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.createRaffle = this.createRaffle.bind(this);
    this.cancelRaffle = this.cancelRaffle.bind(this);
    this.claimRaffle = this.claimRaffle.bind(this);
    this.updateConfig = this.updateConfig.bind(this);
    this.modifyRaffle = this.modifyRaffle.bind(this);
    this.buyTicket = this.buyTicket.bind(this);
    this.receive = this.receive.bind(this);
    this.noisReceive = this.noisReceive.bind(this);
    this.updateRandomness = this.updateRandomness.bind(this);
    this.toggleLock = this.toggleLock.bind(this);
  }

  createRaffle = async ({
    assets,
    owner,
    raffleOptions,
    raffleTicketPrice
  }: {
    assets: AssetInfo[];
    owner?: string;
    raffleOptions: RaffleOptionsMsg;
    raffleTicketPrice: AssetInfo;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      create_raffle: {
        assets,
        owner,
        raffle_options: raffleOptions,
        raffle_ticket_price: raffleTicketPrice
      }
    }, fee, memo, funds);
  };
  cancelRaffle = async ({
    raffleId
  }: {
    raffleId: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      cancel_raffle: {
        raffle_id: raffleId
      }
    }, fee, memo, funds);
  };
  claimRaffle = async ({
    raffleId
  }: {
    raffleId: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      claim_raffle: {
        raffle_id: raffleId
      }
    }, fee, memo, funds);
  };
  updateConfig = async ({
    creationCoins,
    feeAddr,
    maxTicketsPerRaffle,
    minimumRaffleDuration,
    name,
    noisProxyAddr,
    noisProxyCoin,
    owner,
    raffleFee
  }: {
    creationCoins?: Coin[];
    feeAddr?: string;
    maxTicketsPerRaffle?: number;
    minimumRaffleDuration?: number;
    name?: string;
    noisProxyAddr?: string;
    noisProxyCoin?: Coin;
    owner?: string;
    raffleFee?: Decimal;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_config: {
        creation_coins: creationCoins,
        fee_addr: feeAddr,
        max_tickets_per_raffle: maxTicketsPerRaffle,
        minimum_raffle_duration: minimumRaffleDuration,
        name,
        nois_proxy_addr: noisProxyAddr,
        nois_proxy_coin: noisProxyCoin,
        owner,
        raffle_fee: raffleFee
      }
    }, fee, memo, funds);
  };
  modifyRaffle = async ({
    raffleId,
    raffleOptions,
    raffleTicketPrice
  }: {
    raffleId: number;
    raffleOptions: RaffleOptionsMsg;
    raffleTicketPrice?: AssetInfo;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      modify_raffle: {
        raffle_id: raffleId,
        raffle_options: raffleOptions,
        raffle_ticket_price: raffleTicketPrice
      }
    }, fee, memo, funds);
  };
  buyTicket = async ({
    onBehalfOf,
    raffleId,
    sentAssets,
    ticketCount
  }: {
    onBehalfOf?: string;
    raffleId: number;
    sentAssets: AssetInfo;
    ticketCount: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      buy_ticket: {
        on_behalf_of: onBehalfOf,
        raffle_id: raffleId,
        sent_assets: sentAssets,
        ticket_count: ticketCount
      }
    }, fee, memo, funds);
  };
  receive = async ({
    msg,
    sender,
    tokenId
  }: {
    msg: Binary;
    sender: string;
    tokenId: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      receive: {
        msg,
        sender,
        token_id: tokenId
      }
    }, fee, memo, funds);
  };
  noisReceive = async ({
    callback
  }: {
    callback: NoisCallback;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      nois_receive: {
        callback
      }
    }, fee, memo, funds);
  };
  updateRandomness = async ({
    raffleId
  }: {
    raffleId: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_randomness: {
        raffle_id: raffleId
      }
    }, fee, memo, funds);
  };
  toggleLock = async ({
    lock
  }: {
    lock: boolean;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      toggle_lock: {
        lock
      }
    }, fee, memo, funds);
  };
}